wandb_version: 1

epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0001
L1_lambda:
  desc: null
  value: 1.0e-05
L2_lambda:
  desc: null
  value: 0.001
CE_weight:
  desc: null
  value:
  - 0.1
  - 0.7
  - 0.2
img_size:
  desc: null
  value:
  - 32
  - 64
  - 64
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719645036
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
